### ISSUE TITLE
what is "efficient enough"?

### ISSUE THREAD

**Issue by corybrunson** [alstat/ALUES#16]
This might just be a typo, but i want to be sure. In the JOSS manuscript, you say in the "Speed" section, "ALUES is efficient enough in evaluating large sets of land units." Is there a domain-specific threshold these systems are expected to meet, or is this just a general statement that ALUES is fast?

If it's a generic statement, it would be helpful to know whether ALUES is competitive, i.e. how fast other systems are at the same task. If this information is not available, then perhaps the benchmark tests can be presented without a normative claim about their efficiency?

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/4228)._

**Comment by alstat** [comment]
Hi @corybrunson, thank you for your suggestion. I removed the claim of "efficiency" and simply put a benchmark title. See commit [here](https://github.com/alstat/ALUES/commit/96b6134c8122e02baa3d5be2cf818297a603e59c). Should I re-upload the paper to update it?
