### ISSUE TITLE
statement of need in software documentation

### ISSUE THREAD

**Issue by corybrunson** [alstat/ALUES#17]
The statement of need in the JOSS manuscript is very clear. However, one review criteria is that the software documentation itself also contain a statement of need. I don't expect it to be as long as that in the manuscript; a sentence or two in the README or manual could explain what need this package fills.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/4228)._

**Comment by alstat** [comment]
Added Statement of Need to README. Commit [02344b2](https://github.com/alstat/ALUES/commit/02344b25f58b7ff6d2782a2b2383903f3695ab95)
