### ISSUE TITLE
illustrate non-error output elements in overall_suit documentation

### ISSUE THREAD

**Issue by corybrunson** [alstat/ALUES#20]
This is a minor point, but possibly due to an oversight so i wanted to flag it. Here is the first chunk of example code for `overall_suit()`:

```r
library(ALUES)
out <- suit("ricebr", terrain=MarinduqueLT, water=MarinduqueWater, temp=MarinduqueTemp, sow_month=1)
out[["terrain"]]
```

Because the crop requirements don't match the terrain data, the third line contains only an error string. Should a fourth line, e.g. `out[["water"]]`, be added to show the user how the output looks when the crop and environment data are compatible?

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/4228)._

**Comment by alstat** [comment]
Added, thanks. Commit at [5218b75](https://github.com/alstat/ALUES/commit/5218b75a66c849cbc3b984f524d60884f2735a11)
