### ISSUE TITLE
cross-reference documented functions

### ISSUE THREAD

**Issue by corybrunson** [alstat/ALUES#21]
The package contains a large number of data objects, which makes the index a slog to browse. Because there are only three documented functions, all of which are at least indirectly related, i suggest that each function include a link to both others in the "Description" or "See also" section. This would provide easy navigation among them, which is not possible through the index.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/4228)._

**Comment by alstat** [comment]
Added this to See also section. There are only two functions exported, `suit` and `overall_suit` both now have link to each other. Thank you for this suggestion.

**Comment by alstat** [comment]
[Commit at 3676774](https://github.com/alstat/ALUES/commit/36767749d82cde01078776c1e007e4372a0e0693)

**Comment by corybrunson** [comment]
Great, thank you!
