### ISSUE TITLE
misspecified test(s)?

### ISSUE THREAD

**Issue by corybrunson** [alstat/ALUES#22]
While running tests in "test_suitability.R", i encountered a failure on line 50:

```r
test_that("Case A: Triangular", expect_equal(suit$`Suitability Class`["CFragm"][6,], right_tri()[["class"]]))
```

The reason is that one side is a character string while the other side is a factor value.

This might be due to a difference in versions of the testthat package, but i wanted to flag it to check that it's intended and, if not, ask if other similar tests may need to be revised.

(Also, i had to export `suitability()` in order to manually run them, which prompts me to ask: Why is this function documented but not exported? I apologize if i missed an answer somewhere.)

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/4228)._

**Comment by alstat** [comment]
Hi @corybrunson, I not getting an error. Although, I made some fix to the tests, I changed the `suit` variable to `suit_` to avoid conflicting with the exported function `suit`. In case, this might be the reason for errors.

As for the `suitability`, we initially used it as our exported function for computing the suitability score, but we decided to shorten it to `suit` to make it consistent with the `overall_suit` function. So, basically `suit` is a wrapper for `suitability`.

**Comment by corybrunson** [comment]
Hm. I just tried to reproduce the error without updating the repo, so this might have been my fault. Thank you for the explanation!

Regarding `suitability()`, even as a wrapper, it would be good to just include it in the documentation for `suit()`, if it's going to be exported. But it wouldn't require anything more that a sentence saying that it's a wrapper. Is there a specific reason not to?

**Comment by alstat** [comment]
Thank you @corybrunson, the specific reason as to why `suitability()` function is not documented in `suit()` is the fact that it is not an exported function.

**Comment by corybrunson** [comment]
I'm sorry! I mixed up my own earlier question. Thanks for clarifying!
